### ISSUE TITLE
unexpected '['

### ISSUE THREAD

**Issue by Busfreak** [BlueTeck/kanboard_plugin_metadata#12]
Parse error: syntax error, unexpected '[' in /var/www/kanboard/plugins/Metadata/Controller/Metadata.php on line 51 

`$this->projectMetadata->save($project['id'], [$values['key'] => $values['value']]);`
Array not recognized, because of PHP version?
`$this->userMetadata->save($user['id'], array($values['key'] => $values['value']));`
works.

Configuration

```
Version: master
PHP version: 5.3.10-1ubuntu3.21
PHP SAPI: apache2handler
OS version: Linux 3.2.0-97-generic-pae
Datenbanktreiber mysql
Database version: 5.5.46-0ubuntu0.12.04.2
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
```

**Comment by TimoStahl** [comment]
Thx, changed it for older PHP Versions
- Short-Arry-Syntax PHP 5.4
