### ISSUE TITLE
side effect with screenshots

### ISSUE THREAD

**Issue by Busfreak** [BlueTeck/kanboard_plugin_metadata#13]
Hi Timo,

I found a side effect:
https://github.com/fguillot/kanboard/issues/1979#issuecomment-199871296

When Metadata is installed, the screenshots are not shown.

![image1](https://cloud.githubusercontent.com/assets/12938119/13960494/d93c2d64-f058-11e5-8ad5-fc07b08ba9fa.jpg)
![image2](https://cloud.githubusercontent.com/assets/12938119/13960501/de89ed9c-f058-11e5-84df-dcb3b7e25dbe.jpg)

I don't know why :disappointed:

**Comment by Busfreak** [comment]
forget about this! translations.php was not encoded utf-8
created a PR :smile:

**Comment by TimoStahl** [comment]
okay :)
