### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by jtourt** [BlueTeck/kanboard_plugin_metadata#17]
Timo,

I started using this plugin today to edit metadata that will be used to interface Kanboard with my workplace's ticket system (BMC FootPrints).  Your plugin works nicely.  Just what I needed. 

Thank you for creating, maintaining, and publicly sharing your creation.  This plugin has also provided a useful example of creating a Kanboard plugin.  So, thank you!

**Comment by TimoStahl** [comment]
Thanks for your feedback :smile:
