### ISSUE TITLE
bug d'install

### ISSUE THREAD

**Issue by sebastienlelarge** [BlueTeck/kanboard_plugin_metadata#21]
hello,
i'm french, sorry for my english
i have a problem

i have upload Metadata in the folder Plugins...
but there is an error

''Internal Error: Identifier "language" is not defined.''

help me please...

**Comment by TimoStahl** [comment]
Hi, 
which Kanboard Version do you have?
And which plugin version did you downloaded?

Regards,
Timo

**Comment by sebastienlelarge** [comment]
kanboard : 1.0.27
plugin : Version: 1.0.3

**Comment by TimoStahl** [comment]
If you have Kanboard Version 1.0.27 you need Metadata  1.0.2.

Metadata 1.0.3 => Kanboard 1.0.28
Metadata 1.0.2 => Kanboard 1.0.27

https://github.com/BlueTeck/kanboard_plugin_metadata/releases

**Comment by sebastienlelarge** [comment]
thank you very much

**Comment by Olliiee** [comment]
Same here with Kanboard 1.0.30, Metadata 1.0.29.0

**Comment by TimoStahl** [comment]
Kanboard 1.0.30 => https://github.com/BlueTeck/kanboard_plugin_metadata/releases/tag/1.0.29.0
