### ISSUE TITLE
KB crashes after plugin installation

### ISSUE THREAD

**Issue by adevicef** [BlueTeck/kanboard_plugin_metadata#22]
Hi,

After installing Metadata plugins through the web interface, KB crashes with the message "Internal Error: Unable to migrate schema for the plugin: Metadata => SQLSTATE[HY000]: General error: 8 attempt to write a readonly database".

By the way, I had to manually change the original kanboard_pluing_metadata-1.0.29.0 directory name to Metadata (I saw it as a solution for a different plugin issue).

I'm using KB 1.0.30.

Thanks for such an useful application.

**Comment by TimoStahl** [comment]
Hey,
thanks fpr reporting this issue, which database are you using?

**Comment by adevicef** [comment]
Default SQLite.

**Comment by adevicef** [comment]
I don't know how, but simply rebooting my server apparently fixed the problem. Sorry for not having tried that before, and also sorry for the time you have spent on this.

Thanks for your help!
