### ISSUE TITLE
Constant missing in version 1.33

### ISSUE THREAD

**Issue by msalmonse** [BlueTeck/kanboard_plugin_metadata#26]
I upgrade kanboard to 1.33 today and installed the metadata plugin. I get the following error when I choose the plugins menu item:

PHP Warning:  constant(): Couldn't find constant \Kanboard\Plugin\kanboard_plugin_metadata-1.0.33.0\Schema\VERSION in /Library/Server/Web/Data/Sites/.../app/Core/Plugin/SchemaHandler.php on line 69, referer: https://.../dashboard

**Comment by TimoStahl** [comment]
Hi,

thanks for reporting, the schema is not needed at the moment, I renamed the folder, so it is not executed automatically anymore.
