### ISSUE TITLE
Refactor zip release to conform with plugin:install patterns

### ISSUE THREAD

**Issue by almereyda** [BlueTeck/kanboard_plugin_metadata#30]
When installing this plugin with `plugin:install`, it uncompresses directly into the `PLUGIN_DIR`, without putting itself into its own subfolder. This is a similar behaviour to https://github.com/BlueTeck/kanboard_plugin_coverimage/issues/13#issuecomment-329933085

A suggestion would be to pack the files into the zip within a subfolder Metadata.

**Comment by TimoStahl** [comment]
Sry for my late answer, I will make a new release with a correct zip later.

**Comment by antifob** [comment]
Should be fixed by #31

**Comment by TimoStahl** [comment]
Should be fixed, waiting for the Kanbard Plugin merge https://github.com/kanboard/website/pull/37
