### ISSUE TITLE
$values not set in forms

### ISSUE THREAD

**Issue by Busfreak** [BlueTeck/kanboard_plugin_metadata#9]
![add metadata values](https://cloud.githubusercontent.com/assets/12938119/13928437/e4383a6e-ef95-11e5-9b51-977dcfc5b50d.jpg)

maybe you have to remove $values again?
I don't know why you have put it in the forms, so I didn't change it.

**Comment by TimoStahl** [comment]
The form is used for edit and add, so the values parameter was needed. Should be fixed now.
